name: Testing system, release if push to `main`
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup docker-compose stack
        run: 'npm run ci:run-parse'
      - name: Install ionic
        run: npm install @ionic/cli
      - name: Install dependencies
        run: npm install
      # Runs
      - name: Check docker
        run: docker ps -a && docker-compose logs --tail 10
      - name: Set up DB
        run: 'npm run ci:setup-db'
      - name: Running e2e with cypress
        uses: cypress-io/github-action@v2
        with:
          ## FIXME: run this against the locally deployed version?
          start: npm run serve
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:8080'
  deploy:
    runs-on: ubuntu-latest
    needs: tests # only when tests passed
    if: github.event_name == 'push' # only if this was a push on 'main'
    steps:
      - name: Push changes to production branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: production